### ISSUE TITLE
no image

### ISSUE THREAD

**Issue by ge53** [tyhenry/ofxRealSense#1]
Hi-I am new to Open Frameworks + C++--(used to running my SR300 with javascript)...trying to run your add-on in combo with "tweaked"  ofxRSSDKv2 examples--the files execute, no errors, windows open, camera not on..though the Intel RSSDK examples in C++ run fine. I am using Windows10, VisualStudio 2015, the correct Intel RSSDK r2. Do you have a .sln that you run inyour SR300 i can try?  Thanks for this..

**Comment by tyhenry** [comment]
Will update with an example in next couple days - the interface has changed significantly from ofxRSSDK.

**Comment by tyhenry** [comment]
Ok - just made a quick example: https://github.com/tyhenry/ofxRealSense/tree/master/example-simple

test that out and let me know if you still don't see an image

**Comment by ge53** [comment]
Great! thanks for bring so quick! the sensor works great/i believe the
bottom right frame("depth in color") is throwing these errors (so it
repeats the "depth" image)-
again-thanks..:
[warning] ofxRealSense: unable to acquire new frame, error status: -303
[ error ] ofxRealSense: can't draw depth, no pixels stored
[ error ] ofxRealSense: can't draw color, no pixels stored
[ error ] ofGLUtils: ofGetGLFormatFromPixelFormat(): unknown OF pixel
format-1, returning GL_LUMINANCE
[ error ] ofGLUtils: ofGetGLInternalFormatFromPixelFormat(): unknown OF
pixel format-1, returning GL_RGBA
[ error ] ofTexture: allocate(): ofTextureData has 0 width and/or height:
0x0
[warning] ofGLRenderer: draw(): texture is not allocated
[ error ] ofGLUtils: ofGetGLFormatFromPixelFormat(): unknown OF pixel
format-1, returning GL_LUMINANCE
[ error ] ofGLUtils: ofGetGLInternalFormatFromPixelFormat(): unknown OF
pixel format-1, returning GL_RGBA
[ error ] ofTexture: allocate(): ofTextureData has 0 width and/or height:
0x0
[warning] ofGLRenderer: draw(): texture is not allocated
[warning] ofxRealSense: unable to acquire new frame, error status: -303
[warning] ofxRealSense: unable to acquire new frame, error status: -303


https://geraldineerman.com/wp/

**Comment by tyhenry** [comment]
Sounds like it's working actually.

"depth in color" will appear like a stretched version of "depth", since it's mapped to the color image coordinates.  [It looks like this.](http://icecream.me/uploads/4d2656298ab25f1463fdd06b36cfcb1e.png)

The GL errors are there because the camera hasn't acquired any data for the first few draw loops, nothing to worry about.

The -303 errors are the RealSense SDK complaining that new color/depth frames aren't available.
You can safely ignore this for now (will be fixed once I add threading).

I will upload another example soon that shows the rest of the functionality (LOTS more!)

**Comment by ge53** [comment]
Yay!thanks again, will keep on it ....

https://geraldineerman.com/wp/

**Comment by tyhenry** [comment]
you can add the line

    ofSetLogLevel("ofxRealSense", OF_LOG_ERROR);

in setup() to quiet the -303 warnings
